# Generated by Django 3.0 on 2024-03-17 13:44
import logging
from django.db import migrations


def copy_data_from_source_to_target(apps, schema_editor):
    logger = logging.getLogger(__name__)
    try:
        SourceProfile = apps.get_model("oc_lettings_site", "Profile")
        TargetProfile = apps.get_model("profiles", "Profile")
        for item in SourceProfile.objects.all():
            TargetProfile.objects.create(
                user=item.user, favorite_city=item.favorite_city
            )
    except LookupError as e:
        logger.error(
            f"{e} - The Database has failed to import before data, now, the db is empty for profile objects."
        )


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.RunPython(copy_data_from_source_to_target),
    ]
