# Generated by Django 3.0 on 2024-03-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20240317_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
