name: OC-Lettings 2.0 CI/CD

on:
  push: 
    branches-ignore:
      - 'none'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        id: Build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: ${{ needs.Build.result == 'success' }}
    steps:
      - name: Run Tests
        id: Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        run: |
          pytest -v
          
  Code_quality:
    runs-on: ubuntu-latest
    needs: Test
    if: ${{ needs.Test.result == 'success' }}
    steps:
      - name: Run check code quality
        id: Code_quality
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        run: |
          flake8 .

  deploy:
    runs-on: ubuntu-latest
    needs: Code_quality
    if: ${{ needs.Code_quality.result == 'success' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Deploy to production
        if: github.ref == 'refs/heads/master' 
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
          