name: OC-Lettings 2.0 CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show files after installing dependencies
        run: |
          ls -R

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show files
        run: |
          ls -R
      - name: Install pytest
        run: |
          pip install pytest
      - name: Show files after installing pytest
        run: |
          ls -R
      - name: Run Tests
        id: tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          pytest -v
          
  code_quality:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Show files
        run: |
          ls -R
      - name: Check Code Quality
        uses: PyCQA/flake8-action@v3
