name: OC-Lettings 2.0 CI/CD

on:
  push: 
    branches-ignore:
      - 'none'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Run Tests
        id: tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        run: |
          pytest -v
          
  code_quality:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Run check code quality
        id: code_quality
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        run: |
          flake8 .

  deploy:
    runs-on: ubuntu-latest
    needs: code_quality
    if: ${{ needs.code_quality.result == 'success' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Deploy to production
        if: github.ref == 'refs/heads/master' 
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
          wait-for-success: true
          